import ClientLayout from "./client-layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ServerLayout({ children }) {
  return <ClientLayout>{children}</ClientLayout>;
}
